### PR TITLE
Upgrade to 2.13.1

### PR DESCRIPTION
**Pull request by metab0t**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by metab0t** [comment]
@conda-forge-admin, please rerender

**Comment by metab0t** [comment]
@kyri-petrou Maybe we can merge this?

**Comment by kyri-petrou** [comment]
My apologies @metab0t , I've been meaning to put some time away to properly review the changes, but since I no longer use pandapower nor Python at my current role it's not been possible to do so. [I've approved a PR](https://github.com/conda-forge/pandapower-feedstock/pull/12#pullrequestreview-1439453677) for someone else to be added as a maintainer and planing to remove myself once that's merged in.

If merging this PR is blocking you, I can approve it but full disclaimer I do not have the capacity to review whether it actually works

**Comment by metab0t** [comment]
@conda-forge-admin, please rerender

**Comment by TonyXiang8787** [comment]
@metab0t please perform a down merge. To make sure that my name lands in the maintainer list.

**Review by TonyXiang8787 — CHANGES_REQUESTED** [review]
@metab0t please perform a down merge.

**Pull request merged**
